codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

ignore:
  - "src/__tests__/**/*"
  - "src/**/*.test.ts"
  - "src/**/*.spec.ts"
  - "src/cli.ts"
  - "dist/**/*"
  - "coverage/**/*"
  - "jest.config.js"
  - "*.config.*"
